include Makefile

TEST_SRCS = $(wildcard tests/test_ft_*.c)
TEST_EXES = $(TEST_SRCS:.c=.out)

test: $(TEST_EXES)
	./run_tests.sh

clean_tests:
	rm -f $(TEST_EXES)

%.out: %.c $(NAME)
	$(CC) $(CFLAGS) -I. -o $@ $< $(NAME)

.PHONY: test clean_tests
