name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libbsd-dev

    - name: Install Norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette

    - name: Run Norminette
      run: norminette ft_*.c *.h

    - name: Build
      run: |
        export CC=clang
        make

    - name: Run tests
      run: |
        export CC=clang
        make -f Makefile.test test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: libft_artifact
        path: ./libft.a