name: Release

on:
  release:
    types: [created]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libbsd-dev

    - name: Build and create archive
      run: |
        export CC=clang
        make -f Makefile.release release

    - name: Upload release asset (zip)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_UPLOAD_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./$(RELEASE_NAME).zip
        asset_name: $(RELEASE_NAME).zip
        asset_content_type: application/zip

    - name: Upload release asset (a)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_UPLOAD_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./$(NAME)
        asset_name: $(NAME)
        asset_content_type: application/octet-stream
